package ism.dakar.edumanage.security.api.enums;

public enum StatusRequete {
    OK, BAD_REQUEST, UNAUTHORIZED, VALIDATION_EXCEPTION, EXCEPTION, INVALID_ROLES, INVALID_CREDENTIALS,
    NOT_FOUND, DUPLICATE_EMAIL, DUPLICATE_REFERENCE, DUPLICATE_TELEPHONE, CREATED, DELETED, UPDATING_FAILED,
    ACCESS_DENIED, ACCOUNT_LOCKED, SESSION_TIMED_OUT, SESSION_CONFIRMATION_NEED, SESSION_CODE_EXPIRED, SESSION_INVALID

}
