spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/edumanage
    username: postgres
    password: edumanage@2025
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

  sql:
    init:
      mode: always   # permet d'exécuter data.sql ou schema.sql si présent
